cmd_drivers/gpu/mali400/r4p0/__malidrv_build_info.o := /home/parthib/toolchains/ubarm-eabi-4.9/bin/arm-eabi-gcc -Wp,-MD,drivers/gpu/mali400/r4p0/.__malidrv_build_info.o.d  -nostdinc -isystem /home/parthib/toolchains/ubarm-eabi-4.9/bin/../lib/gcc/arm-eabi/4.9.4/include -I/home/parthib/Desktop/j23g2/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/parthib/Desktop/j23g2/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/parthib/Desktop/j23g2/include/uapi -Iinclude/generated/uapi -include /home/parthib/Desktop/j23g2/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-sc/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -Idrivers/staging/android -DCONFIG_MALI400_PROFILING=1 -DCONFIG_MALI_DMA_BUF_MAP_ON_ATTACH -DCONFIG_MALI_SHARED_INTERRUPTS -DCONFIG_MALI_DT -DCONFIG_MALI400=1 -DSPRD_MEM_OPT_PAGE_TABLE_SHRINK -DSPRD_GPU_BOOST -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=0 -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=0 -DMALI_STATE_TRACKING=1 -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=64 -DUSING_GPU_UTILIZATION=0 -DMALI_ENABLE_CPU_CYCLES=0 -DMALI_UPPER_HALF_SCHEDULING -Idrivers/gpu/mali400/r4p0 -Idrivers/gpu/mali400/r4p0/include -Idrivers/gpu/mali400/r4p0/common -Idrivers/gpu/mali400/r4p0/linux -Idrivers/gpu/mali400/r4p0/linux/license/gpl -Idrivers/gpu/mali400/r4p0/platform -Idrivers/gpu/mali400/r4p0/platform/sc8830 -DSVN_REV_STRING=\"\" -fno-PIC    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(__malidrv_build_info)"  -D"KBUILD_MODNAME=KBUILD_STR(mali)" -c -o drivers/gpu/mali400/r4p0/.tmp___malidrv_build_info.o drivers/gpu/mali400/r4p0/__malidrv_build_info.c

source_drivers/gpu/mali400/r4p0/__malidrv_build_info.o := drivers/gpu/mali400/r4p0/__malidrv_build_info.c

deps_drivers/gpu/mali400/r4p0/__malidrv_build_info.o := \

drivers/gpu/mali400/r4p0/__malidrv_build_info.o: $(deps_drivers/gpu/mali400/r4p0/__malidrv_build_info.o)

$(deps_drivers/gpu/mali400/r4p0/__malidrv_build_info.o):
